const weatherInfo = [
	{
		"code" : 1000,
		"day" : "Солнечно",
		"night" : "Ясно",
		"icon" : 113,
        "imageDay" : '/app/public/weather/64x64/day/113.png',
        "imageNight" : '/app/public/weather/64x64/night/113.png',
	},
	{
		"code" : 1003,
		"day" : "Переменная облачность",
		"night" : "Переменная облачность",
		"icon" : 116,
        "imageDay" : '/app/public/weather/64x64/day/116.png',
        "imageNight" : '/app/public/weather/64x64/night/116.png',
	},
	{
		"code" : 1006,
		"day" : "Облачно",
		"night" : "Облачно",
		"icon" : 119,
        "imageDay" : '/app/public/weather/64x64/day/119.png',
        "imageNight" : '/app/public/weather/64x64/night/119.png',
	},
	{
		"code" : 1009,
		"day" : "Пасмурно",
		"night" : "Пасмурно",
		"icon" : 122,
        "imageDay" : '/app/public/weather/64x64/day/122.png',
        "imageNight" : '/app/public/weather/64x64/night/122.png',
	},
	{
		"code" : 1030,
		"day" : "Туман",
		"night" : "Туман",
		"icon" : 143,
        "imageDay" : '/app/public/weather/64x64/day/143.png',
        "imageNight" : '/app/public/weather/64x64/night/143.png',
	},
	{
		"code" : 1063,
		"day" : "Возможен кратковременный дождь",
		"night" : "Возможен кратковременный дождь",
		"icon" : 176,
        "imageDay" : '/app/public/weather/64x64/day/176.png',
        "imageNight" : '/app/public/weather/64x64/night/176.png',
	},
	{
		"code" : 1066,
		"day" : "Возможен мокрый снег",
		"night" : "Возможен мокрый снег",
		"icon" : 179,
        "imageDay" : '/app/public/weather/64x64/day/179.png',
        "imageNight" : '/app/public/weather/64x64/night/179.png',
	},
	{
		"code" : 1069,
		"day" : "Возможен мокрый снег",
		"night" : "Возможен мокрый снег",
		"icon" : 182,
        "imageDay" : '/app/public/weather/64x64/day/182.png',
        "imageNight" : '/app/public/weather/64x64/night/182.png',
	},
	{
		"code" : 1072,
		"day" : "Возможна кратковременная переохлажденная морось",
		"night" : "Возможна кратковременная переохлажденная морось",
		"icon" : 185,
        "imageDay" : '/app/public/weather/64x64/day/185.png',
        "imageNight" : '/app/public/weather/64x64/night/185.png',
	},
	{
		"code" : 1087,
		"day" : "Возможны грозовые вспышки",
		"night" : "Возможны грозовые вспышки",
		"icon" : 200,
        "imageDay" : '/app/public/weather/64x64/day/200.png',
        "imageNight" : '/app/public/weather/64x64/night/200.png',
	},
	{
		"code" : 1114,
		"day" : "Низовая метель",
		"night" : "Низовая метель",
		"icon" : 227,
        "imageDay" : '/app/public/weather/64x64/day/227.png',
        "imageNight" : '/app/public/weather/64x64/night/227.png',
	},
	{
		"code" : 1117,
		"day" : "Метель",
		"night" : "Метель",
		"icon" : 230,
        "imageDay" : '/app/public/weather/64x64/day/230.png',
        "imageNight" : '/app/public/weather/64x64/night/230.png',
	},
	{
		"code" : 1135,
		"day" : "Туман",
		"night" : "Туман",
		"icon" : 248,
        "imageDay" : '/app/public/weather/64x64/day/248.png',
        "imageNight" : '/app/public/weather/64x64/night/248.png',
	},
	{
		"code" : 1147,
		"day" : "Ледяной туман",
		"night" : "Ледяной туман",
		"icon" : 260,
        "imageDay" : '/app/public/weather/64x64/day/260.png',
        "imageNight" : '/app/public/weather/64x64/night/260.png',
	},
	{
		"code" : 1150,
		"day" : "Местами мелкая морось",
		"night" : "Местами мелкая морось",
		"icon" : 263,
        "imageDay" : '/app/public/weather/64x64/day/263.png',
        "imageNight" : '/app/public/weather/64x64/night/263.png',
	},
	{
		"code" : 1153,
		"day" : "Легкая морось",
		"night" : "Легкая морось",
		"icon" : 266,
        "imageDay" : '/app/public/weather/64x64/day/266.png',
        "imageNight" : '/app/public/weather/64x64/night/266.png',
	},
	{
		"code" : 1168,
		"day" : "Изморозь",
		"night" : "Изморозь",
		"icon" : 281,
        "imageDay" : '/app/public/weather/64x64/day/281.png',
        "imageNight" : '/app/public/weather/64x64/night/281.png',
	},
	{
		"code" : 1171,
		"day" : "Сильный ледяной дождь",
		"night" : "Сильный ледяной дождь",
		"icon" : 284,
        "imageDay" : '/app/public/weather/64x64/day/284.png',
        "imageNight" : '/app/public/weather/64x64/night/284.png',
	},
	{
		"code" : 1180,
		"day" : "Небольшой дождь",
		"night" : "Небольшой дождь",
		"icon" : 293,
        "imageDay" : '/app/public/weather/64x64/day/293.png',
        "imageNight" : '/app/public/weather/64x64/night/293.png',
	},
	{
		"code" : 1183,
		"day" : "Легкий дождь",
		"night" : "Легкий дождь",
		"icon" : 296,
        "imageDay" : '/app/public/weather/64x64/day/296.png',
        "imageNight" : '/app/public/weather/64x64/night/296.png',
	},
	{
		"code" : 1186,
		"day" : "Временами умеренный дождь",
		"night" : "Временами умеренный дождь",
		"icon" : 299,
        "imageDay" : '/app/public/weather/64x64/day/299.png',
        "imageNight" : '/app/public/weather/64x64/night/299.png',
	},
	{
		"code" : 1189,
		"day" : "Умеренный дождь",
		"night" : "Умеренный дождь",
		"icon" : 302,
        "imageDay" : '/app/public/weather/64x64/day/302.png',
        "imageNight" : '/app/public/weather/64x64/night/302.png',
	},
	{
		"code" : 1192,
		"day" : "Временами сильный дождь",
		"night" : "Временами сильный дождь",
		"icon" : 305,
        "imageDay" : '/app/public/weather/64x64/day/305.png',
        "imageNight" : '/app/public/weather/64x64/night/305.png',
	},
	{
		"code" : 1195,
		"day" : "Ливень",
		"night" : "Ливень",
		"icon" : 308,
        "imageDay" : '/app/public/weather/64x64/day/308.png',
        "imageNight" : '/app/public/weather/64x64/night/308.png',
	},
	{
		"code" : 1198,
		"day" : "Слабый ледяной дождь",
		"night" : "Слабый ледяной дождь",
		"icon" : 311,
        "imageDay" : '/app/public/weather/64x64/day/311.png',
        "imageNight" : '/app/public/weather/64x64/night/311.png',
	},
	{
		"code" : 1201,
		"day" : "Умеренный или сильный ледяной дождь",
		"night" : "Умеренный или сильный ледяной дождь",
		"icon" : 314,
        "imageDay" : '/app/public/weather/64x64/day/314.png',
        "imageNight" : '/app/public/weather/64x64/night/314.png',
	},
	{
		"code" : 1204,
		"day" : "Легкий мокрый снег",
		"night" : "Легкий мокрый снег",
		"icon" : 317,
        "imageDay" : '/app/public/weather/64x64/day/317.png',
        "imageNight" : '/app/public/weather/64x64/night/317.png',
	},
	{
		"code" : 1207,
		"day" : "Умеренный или сильный мокрый снег",
		"night" : "Умеренный или сильный мокрый снег",
		"icon" : 320,
        "imageDay" : '/app/public/weather/64x64/day/320.png',
        "imageNight" : '/app/public/weather/64x64/night/320.png',
	},
	{
		"code" : 1210,
		"day" : "Пятнистый легкий снег",
		"night" : "Пятнистый легкий снег",
		"icon" : 323,
        "imageDay" : '/app/public/weather/64x64/day/323.png',
        "imageNight" : '/app/public/weather/64x64/night/323.png',
	},
	{
		"code" : 1213,
		"day" : "Слабый снег",
		"night" : "Слабый снег",
		"icon" : 326,
        "imageDay" : '/app/public/weather/64x64/day/326.png',
        "imageNight" : '/app/public/weather/64x64/night/326.png',
	},
	{
		"code" : 1216,
		"day" : "Неровный умеренный снег",
		"night" : "Неровный умеренный снег",
		"icon" : 329,
        "imageDay" : '/app/public/weather/64x64/day/329.png',
        "imageNight" : '/app/public/weather/64x64/night/329.png',
	},
	{
		"code" : 1219,
		"day" : "Умеренный снег",
		"night" : "Умеренный снег",
		"icon" : 332,
        "imageDay" : '/app/public/weather/64x64/day/332.png',
        "imageNight" : '/app/public/weather/64x64/night/332.png',
	},
	{
		"code" : 1222,
		"day" : "Неровный сильный снег",
		"night" : "Неровный сильный снег",
		"icon" : 335,
        "imageDay" : '/app/public/weather/64x64/day/335.png',
        "imageNight" : '/app/public/weather/64x64/night/335.png',
	},
	{
		"code" : 1225,
		"day" : "Сильный снегопад",
		"night" : "Сильный снегопад",
		"icon" : 338,
        "imageDay" : '/app/public/weather/64x64/day/338.png',
        "imageNight" : '/app/public/weather/64x64/night/338.png',
	},
	{
		"code" : 1237,
		"day" : "Ледяная крупа",
		"night" : "Ледяная крупа",
		"icon" : 350,
        "imageDay" : '/app/public/weather/64x64/day/350.png',
        "imageNight" : '/app/public/weather/64x64/night/350.png',
	},
	{
		"code" : 1240,
		"day" : "Небольшой дождь моросит",
		"night" : "Небольшой дождь моросит",
		"icon" : 353,
        "imageDay" : '/app/public/weather/64x64/day/353.png',
        "imageNight" : '/app/public/weather/64x64/night/353.png',
	},
	{
		"code" : 1243,
		"day" : "Умеренный или сильный ливень",
		"night" : "Умеренный или сильный ливень",
		"icon" : 356,
        "imageDay" : '/app/public/weather/64x64/day/356.png',
        "imageNight" : '/app/public/weather/64x64/night/356.png',
	},
	{
		"code" : 1246,
		"day" : "Проливной ливень",
		"night" : "Проливной ливень",
		"icon" : 359,
        "imageDay" : '/app/public/weather/64x64/day/359.png',
        "imageNight" : '/app/public/weather/64x64/night/359.png',
	},
	{
		"code" : 1249,
		"day" : "Слабый дождь с мокрым снегом",
		"night" : "Слабый дождь с мокрым снегом",
		"icon" : 362,
        "imageDay" : '/app/public/weather/64x64/day/362.png',
        "imageNight" : '/app/public/weather/64x64/night/362.png',
	},
	{
		"code" : 1252,
		"day" : "Умеренный или сильный мокрый снег",
		"night" : "Умеренный или сильный мокрый снег",
		"icon" : 365,
        "imageDay" : '/app/public/weather/64x64/day/365.png',
        "imageNight" : '/app/public/weather/64x64/night/365.png',
	},
	{
		"code" : 1255,
		"day" : "Слабый дождь со снегом",
		"night" : "Слабый дождь со снегом",
		"icon" : 368,
        "imageDay" : '/app/public/weather/64x64/day/386.png',
        "imageNight" : '/app/public/weather/64x64/night/368.png',
	},
	{
		"code" : 1258,
		"day" : "Умеренный или сильный снегопад",
		"night" : "Умеренный или сильный снегопад",
		"icon" : 371,
        "imageDay" : '/app/public/weather/64x64/day/371.png',
        "imageNight" : '/app/public/weather/64x64/night/371.png',
	},
	{
		"code" : 1261,
		"day" : "Легкий душ из ледяной крупы",
		"night" : "Легкий душ из ледяной крупы",
		"icon" : 374,
        "imageDay" : '/app/public/weather/64x64/day/374.png',
        "imageNight" : '/app/public/weather/64x64/night/374.png',
	},
	{
		"code" : 1264,
		"day" : "Умеренный или сильный ливень ледяной крупы",
		"night" : "Умеренный или сильный ливень ледяной крупы",
		"icon" : 377,
        "imageDay" : '/app/public/weather/64x64/day/377.png',
        "imageNight" : '/app/public/weather/64x64/night/377.png',
	},
	{
		"code" : 1273,
		"day" : "Небольшой дождь с грозой",
		"night" : "Небольшой дождь с грозой",
		"icon" : 386,
        "imageDay" : '/app/public/weather/64x64/day/386.png',
        "imageNight" : '/app/public/weather/64x64/night/386.png',
	},
	{
		"code" : 1276,
		"day" : "Умеренный или сильный дождь с грозой",
		"night" : "Умеренный или сильный дождь с грозой",
		"icon" : 389,
        "imageDay" : '/app/public/weather/64x64/day/389.png',
        "imageNight" : '/app/public/weather/64x64/night/389.png',
	},
	{
		"code" : 1279,
		"day" : "Небольшой снежок с грозой",
		"night" : "Небольшой снежок с грозой",
		"icon" : 392,
        "imageDay" : '/app/public/weather/64x64/day/392.png',
        "imageNight" : '/app/public/weather/64x64/night/392.png',
	},
	{
		"code" : 1282,
		"day" : "Умеренный или сильный снег с грозой",
		"night" : "Умеренный или сильный снег с грозой",
		"icon" : 395,
        "imageDay" : '/app/public/weather/64x64/day/395.png',
        "imageNight" : '/app/public/weather/64x64/night/395.png',
	}
]

export default weatherInfo;